dist: xenial
group: travis_latest
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    # Lint
    - python: "3.7"
      stage: lint
      env: TOXENV=lint
    - python: "3.7"
      env: TOXENV=mypy
    - python: "3.7"
      env: TOXENV=manifest

    # Test
    - python: "2.7"
      stage: test
      env: TOXENV=py27-twisted
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34-twisted
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35-twisted
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36-twisted
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=py37-twisted
    - python: "pypy"
      env: TOXENV=pypy-twisted
      dist: trusty
    - python: "pypy"
      env: TOXENV=pypy
      dist: trusty
    - python: "pypy3"
      env: TOXENV=pypy3
      dist: trusty
    - python: "pypy3"
      env: TOXENV=pypy3-twisted
      dist: trusty

    # Prevent breakage by a new releases
    - python: "3.7-dev"
      env: TOXENV=py37
    - python: "3.7-dev"
      env: TOXENV=py37-twisted


    # Docs
    - python: "3.5"
      stage: docs
      env: TOXENV=docs
    - python: "3.7"
      env: TOXENV=pypi-description

  allow_failures:
    - python: "3.7-dev"


install:
  - pip install tox


script:
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov


notifications:
  email: false
